baseurl: /mental-health-rsesource    

include: ['_pages']

collections:
  authors:
    output: true
  pages:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag